name: ui_tool_kit
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Evolverstech/funxtion-ui-sdk.git

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  funxtion: 
    path: /Users/pro/Desktop/Flutter Packages/funxtion_sdk/
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3

  intl: ^0.18.1


  sliver_tools: ^0.2.12
  video_player: ^2.7.2

  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.2
  dio: ^5.4.0

  
  





 
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_gen: ^5.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons_svg/
    - assets/logo.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf           
        - asset: assets/fonts/Poppins-Medium.ttf                    
        - asset: assets/fonts/Poppins-Regular.ttf       
        - asset: assets/fonts/Poppins-SemiBold.ttf                      
        - asset: assets/fonts/Poppins-Thin.ttf
                 
          
                                                                                                              
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
